osx_image: xcode11.3
language: swift
cache: cocoapods

before_install:
- bundle install

install:
- bundle exec pod install
- set -o pipefail

jobs:
  include:
    - stage: lint
      script: swiftlint
    - stage: test
      script: xcodebuild test -enableCodeCoverage YES -workspace ${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator13.2 -destination "OS=13.3,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO | xcpretty
